# -*- coding: utf-8 -*-
"""ML project (california housing)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/126WXcBKQuP7iXjB_2jJV-R2HI52ENF6v
"""

import pandas as pd
df = pd.read_csv('california_housing_train.csv')
df

y=df['median_house_value']
y

x=df.drop('median_house_value',axis=1)
x

from sklearn.model_selection import train_test_split
x_train , x_test ,y_train , y_test =train_test_split(x ,y ,test_size=0.2,random_state=100)
x_train

x_test

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

y_lr_train_pred = lr.predict(x_train)
y_lr_test_pred = lr.predict(x_test)

from sklearn.metrics import mean_squared_error , r2_score
lr_train_mse = mean_squared_error(y_train,y_lr_train_pred)
lr_train_r2 = r2_score(y_train,y_lr_train_pred)
lr_test_mse=mean_squared_error(y_test,y_lr_test_pred)
lr_test_r2 = r2_score(y_test,y_lr_test_pred)

lr_train_mse

lr_test_mse

lr_train_r2

from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(max_depth=2,random_state=100)
rf.fit(x_train,y_train)

y_rf_train_pred = rf.predict(x_train)
y_rf_test_pred = rf.predict(x_test)
rf_train_mse = mean_squared_error(y_train,y_rf_train_pred)
rf_train_r2 = r2_score(y_train,y_rf_train_pred)
rf_test_mse=mean_squared_error(y_test,y_rf_test_pred)
rf_test_r2 = r2_score(y_test,y_rf_test_pred)

y_rf_train_pred

rf_train_mse

import matplotlib.pyplot as plt
plt.scatter(x=y_train,y=y_lr_train_pred)
plt.plot()
plt.ylabel('median house value pred')
plt.xlabel('median house value experiment')
import numpy as np
z=np.polyfit(y_train,y_lr_train_pred , 1)
p=np.poly1d(z)
plt.plot(y_train , p(y_train),'#ff7401')